// constants/cloudinaryAssets.ts — auto-generated by
// HunterX-Backend/scripts/migrate-assets-to-cloudinary.mjs
//
// Static app imagery hosted on Cloudinary instead of bundled into the app
// binary. Do not hand-edit; re-run the migration script and regenerate
// this file instead.

export const CLOUDINARY_ASSETS: Record<string, { uri: string }> = {
  active_campaign_bg: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861185/hunterx/app-assets/active_campaign_bg.jpg' },
  arise_avatar_1: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861187/hunterx/app-assets/arise_avatar_1.png' },
  arise_avatar_10: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861188/hunterx/app-assets/arise_avatar_10.png' },
  arise_avatar_2: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861190/hunterx/app-assets/arise_avatar_2.png' },
  arise_avatar_3: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861192/hunterx/app-assets/arise_avatar_3.png' },
  arise_avatar_4: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861193/hunterx/app-assets/arise_avatar_4.png' },
  arise_avatar_5: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861195/hunterx/app-assets/arise_avatar_5.png' },
  arise_avatar_6: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861196/hunterx/app-assets/arise_avatar_6.png' },
  arise_avatar_7: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861198/hunterx/app-assets/arise_avatar_7.png' },
  arise_avatar_8: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861199/hunterx/app-assets/arise_avatar_8.png' },
  arise_avatar_9: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861200/hunterx/app-assets/arise_avatar_9.png' },
  badge_cursed_bound: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861202/hunterx/app-assets/badge_cursed_bound.jpg' },
  badge_dragon_soul: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861203/hunterx/app-assets/badge_dragon_soul.jpg' },
  badge_phoenix_heart: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861204/hunterx/app-assets/badge_phoenix_heart.jpg' },
  badge_solo_monarch: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861205/hunterx/app-assets/badge_solo_monarch.jpg' },
  badge_speed_strike: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861207/hunterx/app-assets/badge_speed_strike.jpg' },
  badge_stealth_shadow: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861209/hunterx/app-assets/badge_stealth_shadow.jpg' },
  badge_streak_guardian: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861210/hunterx/app-assets/badge_streak_guardian.jpg' },
  badge_titan_force: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861212/hunterx/app-assets/badge_titan_force.jpg' },
  badge_vanguard_shield: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861213/hunterx/app-assets/badge_vanguard_shield.jpg' },
  badge_viper_strike: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861214/hunterx/app-assets/badge_viper_strike.jpg' },
  high_fidelity: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861220/hunterx/app-assets/high_fidelity.png' },
  login_bg: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861223/hunterx/app-assets/login_bg.png' },
  lost_access_bg: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861226/hunterx/app-assets/lost_access_bg.png' },
  nutrition: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861229/hunterx/app-assets/nutrition.jpg' },
  popupsavatar: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861231/hunterx/app-assets/popupsavatar.jpg' },
  rate_hunterx_bg: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861233/hunterx/app-assets/rate_hunterx_bg.jpg' },
  refer_bg: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861235/hunterx/app-assets/refer_bg.png' },
  run: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861235/hunterx/app-assets/run.jpg' },
  screen: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861237/hunterx/app-assets/screen.png' },
  sleep: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861237/hunterx/app-assets/sleep.jpg' },
  threelitterwater: { uri: 'https://res.cloudinary.com/sc8zzixt/image/upload/v1787861238/hunterx/app-assets/threelitterwater.jpg' },
};
